# Generated by Django 4.0.3 on 2022-04-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileJ', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personal_Info',
            new_name='PersonalInfo',
        ),
    ]
