# Generated by Django 4.0.3 on 2022-04-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileJ', '0006_working_exper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='working_Exper',
            new_name='working_Experience',
        ),
    ]
