# Generated by Django 4.0.3 on 2022-04-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileJ', '0009_rename_education_experinceeducatio_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperinceEducatio',
            new_name='Experince',
        ),
    ]
