# Generated by Django 4.0.3 on 2022-04-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileJ', '0010_rename_experinceeducatio_experince'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educatio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('Education', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
