# Generated by Django 4.0.3 on 2022-04-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileJ', '0013_personalinfo_facebook_link_personalinfo_twitter_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='datasend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=255, null=True)),
                ('Subject', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
