# Generated by Django 4.0.3 on 2022-04-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileJ', '0014_datasend'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Langages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
