# Generated by Django 4.0.3 on 2022-04-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileJ', '0015_project_client_project_langages_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='web',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
